trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    VERSION=$(docker run --rm nodered/node-red-docker:slim cat node_modules/node-red/package.json | grep '"version":' | awk -F \" '{ print $4 }')
    echo "##vso[task.setvariable variable=version]$VERSION"
  displayName: 'Read version number from container'  

- task: Docker@2
  displayName: 'Build docker container'  
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dil001/node-red-dashboard'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(version)
      $(version).$(Build.BuildId)
      latest
