apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-node-persistent-storage-0
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
