apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx 
        imagePullPolicy: IfNotPresent
        name: node-red-docker
        volumeMounts:
        - mountPath: /data
          name: node-red-vol
      volumes:
      - name: node-red-vol
        persistentVolumeClaim:
          claimName: red-node-persistent-storage-0
